"""
Artwork data model for Story Crafter.

This model captures illustration prompts for key visual moments in stories,
generated by the Art Director Agent.
"""

from typing import Optional

from pydantic import BaseModel, Field


class IllustrationPrompt(BaseModel):
    """A single illustration prompt for a key story moment.
    
    Attributes:
        scene_description: Brief description of the scene/moment
        visual_prompt: Detailed image generation prompt
        style_notes: Specific style guidance
        placement_suggestion: Where in story this illustration appears
    """
    
    scene_description: str = Field(
        description="Brief description of the scene or moment being illustrated",
        min_length=10,
    )
    visual_prompt: str = Field(
        description="Detailed image generation prompt with composition, lighting, mood, and details",
        min_length=50,
    )
    style_notes: Optional[str] = Field(
        default=None,
        description="Specific style guidance (e.g., 'soft watercolors', 'bold digital art')",
    )
    placement_suggestion: str = Field(
        description="Where in the story this illustration should appear (e.g., 'opening scene', 'climax moment')",
        min_length=5,
    )


class ArtworkModel(BaseModel):
    """Structured representation of illustration prompts for a story.
    
    This model contains multiple illustration prompts that capture
    key visual moments from the story.
    
    Attributes:
        overall_style: The consistent visual style for all illustrations
        color_palette: Dominant colors to maintain consistency
        art_medium: Suggested art medium/technique
        illustrations: List of individual illustration prompts
    """
    
    overall_style: str = Field(
        description="The consistent visual style for all illustrations (e.g., 'whimsical watercolor', 'sleek digital illustration', 'cozy storybook style')",
        min_length=5,
    )
    color_palette: list[str] = Field(
        description="Dominant colors to maintain visual consistency (e.g., ['soft blues', 'coral pink', 'golden yellow'])",
        min_length=2,
    )
    art_medium: str = Field(
        description="Suggested art medium or technique (e.g., 'watercolor', 'digital painting', 'pencil sketch', 'vector illustration')",
        min_length=3,
    )
    illustrations: list[IllustrationPrompt] = Field(
        description="List of illustration prompts for key story moments (typically 3-6 illustrations)",
        min_length=2,
    )

