"""
Character data model for Story Crafter.

This model captures structured information about story characters
generated by the Character Forge Agent.
"""

from typing import Optional

from pydantic import BaseModel, Field


class CharacterModel(BaseModel):
    """Structured representation of a story character.
    
    Attributes:
        name: Character's name
        species: Species or type (e.g., "human", "mermaid", "robot", "dragon")
        role: Character's role in the story (e.g., "protagonist", "mentor", "sidekick")
        physical_traits: List of physical characteristics
        personality_traits: List of personality characteristics
        strengths: Character's strengths and abilities
        weaknesses: Character's weaknesses or vulnerabilities
        motivations: What drives the character
        goals: What the character wants to achieve
        relationships: Optional relationships with other characters
    """
    
    name: str = Field(
        description="Character's name",
        min_length=1,
    )
    species: str = Field(
        description="Species, type, or kind of being (e.g., 'human', 'mermaid', 'robot')",
        min_length=1,
    )
    role: str = Field(
        description="Character's role in the story (e.g., 'protagonist', 'mentor', 'antagonist', 'sidekick')",
        min_length=1,
    )
    physical_traits: list[str] = Field(
        description="List of physical characteristics and appearance details",
        min_length=1,
    )
    personality_traits: list[str] = Field(
        description="List of personality characteristics and behavioral traits",
        min_length=1,
    )
    strengths: list[str] = Field(
        description="Character's strengths, abilities, and positive qualities",
        min_length=1,
    )
    weaknesses: list[str] = Field(
        description="Character's weaknesses, vulnerabilities, or areas for growth",
        min_length=1,
    )
    motivations: str = Field(
        description="What drives the character; their core motivation",
        min_length=1,
    )
    goals: str = Field(
        description="What the character wants to achieve in the story",
        min_length=1,
    )
    relationships: Optional[str] = Field(
        default=None,
        description="Relationships with other characters or important connections",
    )

