"""
Plot data model for Story Crafter.

This model captures structured information about story plots
generated by the Plot Architect Agent.
"""

from typing import Optional

from pydantic import BaseModel, Field


class PlotModel(BaseModel):
    """Structured representation of a story plot.
    
    This follows classic story structure with setup, conflict, rising action,
    climax, and resolution. Also includes hooks for episodic storytelling.
    
    Attributes:
        setup: Initial situation and context (1-2 sentences)
        conflict: The main problem or inciting incident (1-2 sentences)
        rising_action: Series of events building tension (list of 2-4 key moments)
        climax: The peak moment of tension/decision (1-2 sentences)
        resolution: How the conflict is resolved (1-2 sentences)
        themes: Key themes explored in the plot
        episode_hook: Optional hook for continuing the story in future episodes
    """
    
    setup: str = Field(
        description="Initial situation that establishes the story world, characters, and normalcy",
        min_length=10,
    )
    conflict: str = Field(
        description="The main problem, challenge, or inciting incident that disrupts the setup",
        min_length=10,
    )
    rising_action: list[str] = Field(
        description="List of 2-4 key events that build tension and develop the conflict",
        min_length=2,
    )
    climax: str = Field(
        description="The peak moment of tension where the main conflict comes to a head",
        min_length=10,
    )
    resolution: str = Field(
        description="How the conflict is resolved and normalcy is restored (or changed)",
        min_length=10,
    )
    themes: list[str] = Field(
        description="Key themes or lessons explored in the story (e.g., 'friendship', 'courage', 'acceptance')",
        min_length=1,
    )
    episode_hook: Optional[str] = Field(
        default=None,
        description="Optional setup for a future episode or sequel (e.g., 'But little did they know...')",
    )

