"""
World data model for Story Crafter.

This model captures structured information about story worlds/universes
generated by the Worldbuilder Agent.
"""

from typing import Optional

from pydantic import BaseModel, Field


class WorldModel(BaseModel):
    """Structured representation of a story world.
    
    Attributes:
        name: Name of the world/universe
        description: Rich description of the world
        rules: List of world rules, physics, or magic systems
        locations: List of key locations or places in the world
        aesthetic: Visual and tonal aesthetic of the world
    """
    
    name: str = Field(
        description="Name of the story world or universe",
        min_length=1,
    )
    description: str = Field(
        description="Rich, detailed description of the world including its characteristics",
        min_length=10,
    )
    rules: Optional[list[str]] = Field(
        default=None,
        description="List of world rules, physics, magic systems, or governing principles",
    )
    locations: Optional[list[str]] = Field(
        default=None,
        description="List of key locations, places, or landmarks in the world",
    )
    aesthetic: Optional[str] = Field(
        default=None,
        description="Visual and tonal aesthetic of the world (e.g., 'bioluminescent, ethereal')",
    )

